title: "Ocean CDR Atlas, v0"
author: "[C]Worthy"
copyright: "2024"
logo: logo.png

execute:
  execute_notebooks: off
  only_build_toc_files: true
  
repository:
  url: https://github.com/CWorthy-ocean/Ocean-CDR-Atlas-v0
  
html:
  favicon: favicon.ico
  use_issues_button: false
  use_repository_button: true
  home_page_in_navbar: false  